name: 素晴らしの世界
description: Sharing & Coding
meta_description: "My blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://github.marktube.io'
google_analytics: 'UA-96545939-1'
gems: [jekyll-paginate]
mathjax: true

# Details for the RSS feed generator
url:            'http://github.marktube.io'
author:         'Marktube'
