name: 迷いの世界
description: Sharing & Coding
meta_description: "My blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: '/'
domain_name: 'https://marktube.github.io'
google_analytics: 'UA-96545939-1'
gems: [jekyll-paginate]
mathjax: true

# Details for the RSS feed generator
url:            '/'
author:         'Marktube'
