name: Chaos World
description: Sharing & Coding
meta_description: "My blog"
permalink: /:year/:month/:day/:title

markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
baseurl: '/'
domain_name: 'https://marktube.github.io/'
google_analytics: 'UA-96545939-1'
plugins: [jekyll-paginate]
mathjax: true

# Details for the RSS feed generator
url:            'https://marktube.github.io/'
author:         'Marktube'
